from typing import Any, Protocol

from app.api.schemas.responses import LLMHealthResponse


class LLMClient(Protocol):
    provider: str
    model: str

    async def generate_json(self, system_prompt: str, user_prompt: str) -> dict[str, Any]:
        """Return parsed JSON generated by the provider."""

    async def health_check(self) -> LLMHealthResponse:
        """Return provider health and configured model availability."""
